name: sleep_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  light: ^3.0.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  sensors_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
